package output_formatter

import (
	"regexp"
	"strings"
)

// SimpleMDToHTML converts the specific Old Fox Markdown format to mobile-friendly HTML
func SimpleMDToHTML(mdContent string) string {
	lines := strings.Split(mdContent, "\n")
	var html strings.Builder

	// Write Header with Mobile-Friendly CSS
	html.WriteString(`<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DeepSeek 老狐狸鉴股报告</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: #f5f5f7;
            color: #1d1d1f;
            line-height: 1.6;
            padding: 20px;
            margin: 0;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: #ffffff;
            padding: 25px;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }
        h1 {
            color: #e53935;
            font-size: 24px;
            margin-bottom: 5px;
            text-align: center;
        }
        .meta {
            text-align: center;
            color: #86868b;
            font-size: 14px;
            margin-bottom: 20px;
        }
        blockquote {
            background: #fff3e0;
            border-left: 4px solid #ff9800;
            margin: 15px 0;
            padding: 10px 15px;
            color: #ef6c00;
            font-style: italic;
            border-radius: 4px;
        }
        h2 {
            font-size: 18px;
            color: #1d1d1f;
            margin-top: 30px;
            border-bottom: 1px solid #e5e5ea;
            padding-bottom: 8px;
        }
        strong {
            color: #d32f2f;
        }
        hr {
            border: 0;
            height: 1px;
            background: #e5e5ea;
            margin: 20px 0;
        }
        p {
            margin-bottom: 15px;
			white-space: pre-wrap; /* Preserve newlines */
        }
		.stock-card {
			margin-bottom: 20px;
		}
    </style>
</head>
<body>
<div class="container">
`)

	// Simple Parsing Logic
	for _, line := range lines {
		line = strings.TrimSpace(line)

		if line == "" {
			continue
		}

		if strings.HasPrefix(line, "# ") {
			// H1
			title := strings.TrimPrefix(line, "# ")
			html.WriteString("<h1>" + title + "</h1>\n")
		} else if strings.HasPrefix(line, "**生成时间**") {
			// Meta
			html.WriteString("<div class='meta'>" + parseBold(line) + "</div>\n")
		} else if strings.HasPrefix(line, "> ") {
			// Blockquote
			quote := strings.TrimPrefix(line, "> ")
			html.WriteString("<blockquote>" + parseBold(quote) + "</blockquote>\n")
		} else if strings.HasPrefix(line, "## ") {
			// H2 (Stock Title)
			title := strings.TrimPrefix(line, "## ")
			html.WriteString("<h2>" + title + "</h2>\n")
		} else if strings.HasPrefix(line, "---") {
			// HR
			html.WriteString("<hr>\n")
		} else {
			// Paragraph
			html.WriteString("<p>" + parseBold(line) + "</p>\n")
		}
	}

	html.WriteString(`
    <div class="meta" style="margin-top: 40px;">
        Generated by AI Dragon Sniper System
    </div>
</div>
</body>
</html>`)

	return html.String()
}

func parseBold(text string) string {
	// Simple regex for **Bold** -> <strong>Bold</strong>
	re := regexp.MustCompile(`\*\*(.*?)\*\*`)
	return re.ReplaceAllString(text, "<strong>$1</strong>")
}
