package hold_kline

import (
	"dragon-quant/config"
	"fmt"
	"os"
	"time"
)

func GenerateHoldReport(cfg *config.Config, results []StockResult) {
	f, err := os.Create(cfg.HoldKlineReportFile)
	if err != nil {
		fmt.Printf("Cannot create file %s: %v\n", cfg.HoldKlineReportFile, err)
		return
	}
	defer f.Close()

	html := `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>30分钟级别持仓深度分析</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f5f7fa; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1000px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 12px rgba(0,0,0,0.1); }
        h1 { text-align: center; color: #2c3e50; margin-bottom: 30px; }
        .card { border-bottom: 1px solid #eee; padding: 20px 0; }
        .card:last-child { border-bottom: none; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px; }
        .stock-name { font-size: 24px; font-weight: bold; color: #e74c3c; }
        .stock-code { font-size: 16px; color: #7f8c8d; margin-left: 10px; }
        .review-box { background: #fdf6ec; border-left: 5px solid #e6a23c; padding: 15px; border-radius: 4px; line-height: 1.6; }
        .review-box p { margin: 0; white-space: pre-wrap; }
        .footer { text-align: center; margin-top: 40px; color: #999; font-size: 12px; }
        .timestamp { font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ 30分钟级别持仓/关注深度扫描</h1>
        <div style="text-align: center; margin-bottom: 20px;">
            <span class="timestamp">生成时间: ` + time.Now().Format("2006-01-02 15:04:05") + `</span>
        </div>
`

	for _, r := range results {
		// Convert Markdown in AIReview to HTML roughly (newlines)
		// Or just stick it in pre-wrap

		html += fmt.Sprintf(`
        <div class="card">
            <div class="header">
                <div>
                    <span class="stock-name">%s</span>
                    <span class="stock-code">%s</span>
                </div>
            </div>
            <div class="review-box">
                <p><strong>🧠 DeepSeek 分析:</strong></p>
                <br>
                <p>%s</p>
            </div>
        </div>
`, r.Name, r.Code, r.AIReview)
	}

	html += `
        <div class="footer">
            Generated by AI Dragon Quant System (Hold Kline Module)
        </div>
    </div>
</body>
</html>`

	f.WriteString(html)
	fmt.Printf("\n✅ 报告已生成: %s\n", cfg.HoldKlineReportFile)
}
